services:
  - type: web
    name: helpdesk-api
    runtime: node
    rootDir: server
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /api/health

    envVars:
      - key: MONGODB_URI
        sync: false

      - key: JWT_SECRET
        generateValue: true

      - key: CLIENT_URL
        sync: false

      - key: REDIS_URL
        fromService:
          name: helpdesk-redis
          type: keyvalue
          property: connectionString

      - key: RESEND_API_KEY
        sync: false

      - key: RESEND_FROM_EMAIL
        sync: false

      - key: CLOUDINARY_CLOUD_NAME
        sync: false

      - key: CLOUDINARY_API_KEY
        sync: false

      - key: CLOUDINARY_API_SECRET
        sync: false

  - type: keyvalue
    name: helpdesk-redis
    plan: free
    maxmemoryPolicy: noeviction
    ipAllowList: []
